export default [
    '01100010 01101100 01101110 01110001',
    'Abracadabra',
    'Alexa',
    'Almost there',
    'Beep Bop Beep',
    'Bippity Boppity Boo',
    'Bish Bash Bosh',
    'Building Cool Stuff',
    'By the Power of Grayskull',
    'Crunching Numbers',
    "Can't stop, won't stop",
    'Dont Blnq Now',
    "Don't stop believing",
    "Don't look down",
    'Elementary, my dear Watson',
    'Float like a butterfly, sting like a bee',
    'Good artists copy, great artists steal',
    'Grinding Gears',
    "Half of these ideas are Saqib's",
    'Hasta la vista, baby',
    "Here's Johnny!",
    "Here's looking at you, kid",
    'Hey You Guys!!',
    'Huzzah!',
    'I am your father',
    'I coulda had class. I coulda been a contender',
    "I'll be back",
    "I'll have what she's having",
    'If you build it, they will come',
    'Important Stuff Going On',
    'Inconceivable!',
    "It's alive! It's alive!",
    'Just keep swimming',
    'Keep going!',
    'Magic Mirror on the wall, who is the fairest one of all?',
    'May the Force be with you',
    'My precious',
    'No, I Am Your Father',
    'Nobody puts Baby in a corner',
    'Peforming Magic',
    'Pew! Pew! Pew!',
    "Roads? Where we're going we don't need roads",
    'Shazam!',
    'Stay Hungry, Stay Foolish',
    'Swoooooosh',
    "That'll do, pig. That'll do",
    "That's Not a Knife",
    "These aren't the Droids you're looking for",
    'Thinking and a Blnqing',
    'To Infinity... And Beyond!',
    'Toasty',
    'Tooooooooooo Good',
    "We're not in Kansas anymore",
    'Wax On, Wax Off',
    'Yo Adrian',
    'You had me at ‘hello.’',
    "You're doing Amazing",
    'Zip Zip Zip',
    '¯\\_(ツ)_/¯'
];
