# docker-compose.yml

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    ports: 
      - '5432:5432'
    volumes:
      - blnq-db:/var/lib/postgresql/data

  blnq:
    environment:
      PG_HOST: host.docker.internal
    env_file: .env
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '3000:8080'
        
volumes:
  blnq-db:
