export default {
    isDirty: false,
    hasConfig: false,
    saving: false,
    html: '',
    css: '',
    js: '',
    json: '',
    library: '',
    snippets: [],
    files: [],
    sharing: [],
    blnqName: '',
    displayname: '',
    description: '',
    hasBeenSaved: false,
    showConfig: false,
    showHistory: false,
    showPreferences: false,
    ispublic: false,
    isPermissioned: false,
    module: false,
    user: null
};
